### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by leslie-ds** [mjkwon2021/CAT-Net#17]
How to train a model consistent with CAT_full_v1 performance？

**Comment by CauchyComplete** [comment]
Just use datasets shown in WACV paper using default settings

**Comment by leslie-ds** [comment]
> Just use datasets shown in WACV paper using default settings

thanks for your replay，Is the RGB stream only trained using the original HRNet?

**Comment by CauchyComplete** [comment]
The RGB stream has identical architecture as HRNet, which is a great network for learning fine details in the RGB domain.
The reasons for choosing HRNet as the backbone is illustrated in both papers.
