### ISSUE TITLE
About training dataset 'Fantastic Reality'

### ISSUE THREAD

**Issue by siriusPRX** [mjkwon2021/CAT-Net#40]
Hi, your work is really fascinating to me .Can you offer me some help about the access to the datasets of the fantastic reality dataset? It is really hard to fetch, really need your help!. Thanks a lot !

**Comment by CIawevy** [comment]
same asking ！really need this dataset while training！

**Comment by CauchyComplete** [comment]
Email me.

**Comment by CauchyComplete** [comment]
Update: So many people are asking me for the FantasticReality dataset. If you need this for reproducing CAT-Net results, email me via **mjkwon2021@gmail.com**
Please don't send emails to any other email addresses !!
Don't send emails to my professor or 2nd/3rd authors!! They won't reply about this issue.

**Comment by CauchyComplete** [comment]
I just discovered that some emails have been ending up in the spam folder. Please avoid using domains specific to certain countries. I recommend using your school or work email instead.

**Comment by kummbyte** [comment]
> I just discovered that some emails have been ending up in the spam folder. Please avoid using domains specific to certain countries. I recommend using your school or work email instead.

I sent you an email using my school email address this time. Can you check if you received it? Thank you!

**Comment by kummbyte** [comment]
> I just discovered that some emails have been ending up in the spam folder. Please avoid using domains specific to certain countries. I recommend using your school or work email instead.

Hi，I have sent you my information via email. Please check it. Thank you！

**Comment by STARRY2001** [comment]
@CauchyComplete  Hello! I just sent you an email to apply for the Fantastic Reality Dataset. I really need it, thank you very much!

**Comment by mjkwon2021** [comment]
New visitors are recommended to see: https://github.com/mjkwon2021/CAT-Net/issues/51

**Comment by shenbushou** [comment]
FantasticReality dataset
wanfujun1@gmail.com
need your help!. Thanks a lot !
