### ISSUE TITLE
fusion part

### ISSUE THREAD

**Issue by Cococc2** [mjkwon2021/CAT-Net#46]
Can you tell me where this fusion part is in the code? I can't find it. Thank you.
![image](https://github.com/mjkwon2021/CAT-Net/assets/119996653/441c830b-c0e0-4644-9692-38652a6f28ad)
:D

**Comment by CauchyComplete** [comment]
The Fusion Stage is called stage 5 in the model file.
Refer: [Code here](https://github.com/mjkwon2021/CAT-Net/blob/f1716b0849eb4d94687a02c25bf97229b495bf9e/lib/models/network_CAT.py#L531)

**Comment by Cococc2** [comment]
> 融合阶段在模型文件中称为阶段 5。参考：[代码在这里](https://github.com/mjkwon2021/CAT-Net/blob/f1716b0849eb4d94687a02c25bf97229b495bf9e/lib/models/network_CAT.py#L531)
Thanks！😀
